# -*- coding: utf-8 -*-
"""BirdClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1756g0FleFDl_nvdSQvi0i3q7C7UDLS
"""

# Commented out IPython magic to ensure Python compatibility.
try:
    # %tensorflow_version only exists in Colab.
    # %tensorflow_version 1.x
except Exception:
    pass

import itertools
import os

import matplotlib.pylab as plt
import numpy as np

import tensorflow as tf
import tensorflow_hub as hub

print("TF version:", tf.__version__)
print("Hub version:", hub.__version__)
print("GPU is", "available" if tf.test.is_gpu_available() else "NOT AVAILABLE")

!pip install imageai
!git clone https://github.com/Carson-Tang/Bird-Classifier.git
!ls

from imageai.Prediction.Custom import ModelTraining

from tensorflow.keras.utils import convert_all_kernels_in_model


model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("/content/Bird-Classifier")
model_trainer.trainModel(num_objects=75,
                         num_experiments=150,
                         enhance_data=True,
                         batch_size=32,
                         show_network_summary=False)
